#include "own_reflect_item.h"

/* 静态变量在此实现 */

REFLECT_STRUCT_BEGIN(osize)
REFLECT_STRUCT_MEMBER(width)
REFLECT_STRUCT_MEMBER(height)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(ogrid)
REFLECT_STRUCT_MEMBER(row)
REFLECT_STRUCT_MEMBER(col)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(oimage)
REFLECT_STRUCT_MEMBER(name)
REFLECT_STRUCT_MEMBER(path)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(ofont)
REFLECT_STRUCT_MEMBER(key)
REFLECT_STRUCT_MEMBER(extent)
REFLECT_STRUCT_MEMBER(weight)
REFLECT_STRUCT_MEMBER(name)
REFLECT_STRUCT_MEMBER(style)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(orgba)
REFLECT_STRUCT_MEMBER(red)
REFLECT_STRUCT_MEMBER(green)
REFLECT_STRUCT_MEMBER(blue)
REFLECT_STRUCT_MEMBER(alpha)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(ocategory)
REFLECT_STRUCT_MEMBER(categories)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(obutton)
REFLECT_STRUCT_MEMBER(id)
REFLECT_STRUCT_MEMBER(size)
REFLECT_STRUCT_MEMBER(icon)
REFLECT_STRUCT_MEMBER(font)
REFLECT_STRUCT_MEMBER(colors)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(obtngrp)
REFLECT_STRUCT_MEMBER(id)
REFLECT_STRUCT_MEMBER(offset)
REFLECT_STRUCT_MEMBER(btns)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(oresolution)
REFLECT_STRUCT_MEMBER(size)
REFLECT_STRUCT_MEMBER(image)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(oscreen)
REFLECT_STRUCT_MEMBER(index)
REFLECT_STRUCT_MEMBER(grid)
REFLECT_STRUCT_MEMBER(resogrp)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(ocomponent)
REFLECT_STRUCT_MEMBER(fonts)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(osetting)
REFLECT_STRUCT_MEMBER(btngrp)
REFLECT_STRUCT_END


REFLECT_STRUCT_BEGIN(oconfig)
REFLECT_STRUCT_MEMBER(trayed)
REFLECT_STRUCT_MEMBER(category)
REFLECT_STRUCT_MEMBER(screen)
REFLECT_STRUCT_MEMBER(btngrp)
REFLECT_STRUCT_MEMBER(element)
REFLECT_STRUCT_MEMBER(pagebar)
REFLECT_STRUCT_MEMBER(setting)
REFLECT_STRUCT_END




